config/routes.rb
Rails.application.routes.draw do

  root :to => 'dashboards#index'
  devise_for :agents

  resources :agents do
    collection do
      post :index 
      post :cnew
      post :search
      post :activate_agent
    end
  end    

  resources :listings do
    collection do
      post :search
      post :activate_listing
    end
  end

  resources :users do
    collection do
      post :index
      post :activate_user
    end
  end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	has_one :listing_pic

	has_attached_file :avatar, 
    :path => ":rails_root/public/listing/:class/:attachement/:id/:basename_:style.:extension",
    :url => "/listing/:class/:attachement/:id/:basename_:style.:extension",
    :styles => {
      :thumb    => ['100x100#',  :jpg, :quality => 70],
      :preview  => ['480x480#',  :jpg, :quality => 70],
      :large    => ['600>',      :jpg, :quality => 70],
      :retina   => ['1200>',     :jpg, :quality => 30]
    },
    :convert_options => {
      :thumb    => '-set colorspace sRGB -strip',
      :preview  => '-set colorspace sRGB -strip',
      :large    => '-set colorspace sRGB -strip',
      :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
    }

  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def destroy
  	ListingPic.where('listing_id=?', self.id).destroy_all
  	self.delete
  end

	def activate?
    value = self.status == 'Active' ? 'Inactive' : 'Active'
    self.status = value
    self.save
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_agent!
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  def index
    if flash[:search].blank?
      @listings = Listing.all
    else
      @listings = Listing.all
      s_params = flash[:search]

      if !s_params["status"].blank?
        @listings = @listings.where( :status=>s_params["status"] )
        @status = s_params["status"]
      end

      if !s_params["state"].blank?
        @listings = @listings.where( :state=>s_params["state"] )
        @state = s_params["state"]
      end

      if !s_params["search"].blank?
        @search = s_params["search"]
        @listings = @listings.where("walk_score LIKE ? OR beds LIKE ? OR baths LIKE ? OR year_built LIKE ?", "%#{@search}%", "%#{@search}%", "%#{@search}%", "%#{@search}%")
      end
    end

    @cur_id = current_agent.id
    @listing = Listing.new
  end

  def show
    @agents = Agent.select(:first_name).where('id!=?', 1)
    @agents = @agents.map {|c| c.first_name}
    @pics = ListingPic.where('listing_id=?', @listing.id )
  end

  def new
    @listing = Listing.new
  end

  def edit
  end

  def activate_listing
    @listing = Listing.find(params[:format])
    @listing.activate?
    redirect_to listing_path(@listing)
  end

  def search
    redirect_to listings_path, flash: { search: search_params }
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.status = 'Active'

    respond_to do |format|
      if @listing.save
        @pic = ListingPic.new(pic_params)
        @pic.listing_id = @listing.id
        @pic.save 

        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def listing_params
      params.require(:listing).permit(:listing_type, :state, :year_built, :lot_size, :price_per_sqft, :beds, :walk_score, :mls_id, :description, :status)
    end

    def pic_params
      params.require(:listing).permit(:avatar)
    end

    def search_params
      params.permit(:status, :state, :listing_type, :search)
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-6">
    <div class="field">
      <label>Type:</label>
      <%= f.text_field :listing_type, :class=>'form-control', :required=>true, autocomplete: "off"%>
    </div>    
    <div class="field">
      <label>State:</label>
      <%= f.text_field "state", :class=>'form-control', :required=>true, autocomplete: "off"%>
    </div>    
    <div class="field">
      <label>Year built:</label>
      <%= f.number_field "year_built", :class=>'form-control', :required=>true, autocomplete: "off"%>
    </div>    
    <div class="field">
      <label>Lot size:</label>
      <%= f.number_field "lot_size", :class=>'form-control', :required=>true %>
    </div>
    <div class="field">
      <label>Price per sqft:</label>
      <%= f.number_field "price_per_sqft", :class=>'form-control', :required=>true %>
    </div>
    <div class="field">
      <label>Beds:</label>
      <%= f.number_field "beds", :class=>'form-control', :required=>true %>
    </div>
    <div class="field">
      <label>Walk score:</label>
      <%= f.number_field "walk_score", :class=>'form-control', :required=>true %>
    </div>
    <div class="field">
      <label>MLS ID:</label>
      <%= f.number_field "mls_id", :class=>'form-control', :required=>true %>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="field">
      <label style="vertical-align: top;">Description:</label>
      <%= f.text_area "description", :class=>'form-control', :required=>true, :rows=>'6' %>
    </div>
    <div class="field">
      <label>Agent:</label>
      <%= f.text_field "agent_id", :class=>'form-control', :required=>true, autocomplete: "off", :value=>@cur_id, :readonly=>true %>
    </div>
    <div class="field">
      <label>Pictures:</label>
      <label for="listing_avatar" class="custom-file-upload" style="border:1px solid #9A9590;padding:0.5em;color:#9A9590;width:auto;border-radius:5px;">
        <i class="fa fa-plus-circle" style="font-size:2em;"></i>
      </label>
      <!-- <input id="listing_avatar" type="file" name="listing[avatar]" required="required" /> -->
      <%= f.file_field :avatar, :style=>'display:none;' %>
    </div>
    <div class="hidden-md hidden-sm hidden-xs">
      <br/><br/><br/><br/>
    </div>
    <div class="field" style="text-align:right;">
      <%= f.submit( :class=>'btn btn-primary', :id=>'btn_createlisting') do %>
        Create Listing
      <% end %>
    </div>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<% content_for(:side_bar) do %>
  <%= render 'dashboards/leftsidebar' %>
<% end %>

<div class="div-listings">
  <div class="col-lg-12">
    <div class="div-newagent">
      <button class="btn btn-success" data-toggle="modal" id="btn_newlisting">Create Listing</button>
    </div>
    <div class="div-search">
      <%= simple_form_for(:agents, url: search_listings_path, method: :post) do %>
        <div class="col-lg-8 div-nopadding">
          <div class="col-lg-4 div-margin-bottom">
            <label>Status:</label>
            <%= select_tag "status", options_for_select(["", "Active", "Inactive" ], @status), :class=>'js-select', "data-placeholder" => "Status..." %>
          </div>
          <div class="col-lg-4 div-margin-bottom">
            <label>State:</label>
            <%= select_tag "state", options_for_select(t('state_names'), @state), :class=>'js-select', "data-placeholder" => "State..."  %>
          </div>
          <div class="col-lg-4 div-margin-bottom">
            <label>Type:</label>
            <%= select_tag "type", options_for_select(["", "Apartment", "Single"], @listing_type), :class=>'js-select', "data-placeholder" => "Type..."  %>
          </div>
        </div>
        <div class="col-lg-4 div-nopadding">
          <div class="col-lg-8 div-margin-bottom">
            <label>Search:</label>
            <%= text_field_tag "search", nil, :class=>"form-control", :autocomplete=>:off, :value=>@search %>
          </div>
          <div class="col-lg-4">
            <%= button_tag(type: 'submit', :class=>'btn btn-primary') do %>
              Search
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="div-existing">
      <div class="table-responsive">
        <table id="table_listings">
          <thead>
            <tr>
              <th>Listing ID</th>
              <th>Type</th>
              <th>State</th>
              <th>Walk Score</th>
              <th>Beds</th>
              <th>Baths</th>
              <th>Year Built</th>
              <th>Lot size</th>
              <th>Price per Sqft</th>
              <th>Status</th>
              <th colspan="2" class="text-center">Action</th>
            </tr>
          </thead>

          <tbody>
            <% @listings.each do |listing| %>
              <tr data-link="<%= listing_path(listing.id)%>">
                <td>L<%= listing.id %></td>
                <td><%= listing.listing_type %></td>
                <td><%= listing.state %></td>
                <td><%= listing.walk_score %></td>
                <td><%= listing.beds %></td>
                <td><%= listing.baths %></td>
                <td><%= listing.year_built %></td>
                <td><%= listing.lot_size %></td>
                <td><%= listing.price_per_sqft %></td>
                <td><%= listing.status %></td>
                <td>
                  <%= link_to listing, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-sm btn-danger btn-action' do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                </td>
                <td><%= link_to 'view/edit', listing_path(listing), :class=>'btn btn-sm btn-primary btn-action' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div> 

<div class="modal fade" id="newListing" tabindex="-1" role="dialog" aria-labelledby="newListingLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="newAgentLabel">New Listing Creator</h4>
      </div>
      <div class="modal-body" style="overflow:hidden">
        <%= render 'form' %>
      </div>
      <div class="modal-body">

      </div>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<% content_for(:side_bar) do %>
	<%= render 'dashboards/leftsidebar' %>
<% end %>

<%= form_for(@listing) do |f| %>
  <div class="div-listings">
    <div class="col-lg-12">
      <div class="div-backlisting">
        <%= link_to '< Back', listings_path, :class=>'btn btn-default' %>
      </div>
      <div class="div-showing">
      	<div class="col-lg-11" style="padding: 0 0">
      		<div class="col-lg-2">
	          <div class="field">
	            <%= f.label :id, 'Listing ID:' %>
	            <%= @listing.id %>
	          </div>
	          <div class="hidden-md hidden-sm hidden-xs">
	            <br/><br/>
	          </div>
	          <div class="field">
	            <%= f.label :status, 'Status:' %>
							<span class="<%= @listing.status == 'Active' ? 'active' : 'inactive' %>">
								<%= @listing.status %>
							</span>
	          </div>
	        </div>
	        <div class="col-lg-2">
	          <div class="field">
	            <%= f.label :listing_type, 'Type:' %>
	            <%= @listing.listing_type %>
	          </div>
	          <div class="hidden-md hidden-sm hidden-xs">
	            <br/><br/>
	          </div>
	          <div class="field">
	            <%= f.label :state, 'State:' %>
	            <%= @listing.state %>
	          </div>
	        </div>
	        <div class="col-lg-2">
	          <div class="field">
	            <%= f.label :walk_score, 'Walk score:' %>
	            <%= @listing.walk_score %>
	          </div>
	          <div class="hidden-md hidden-sm hidden-xs">
	            <br/><br/>
	          </div>
	          <div class="field">
	            <%= f.label :beds, 'Beds:' %>
	            <%= @listing.beds %>
	          </div>
	        </div>
	        <div class="col-lg-2">
	          <div class="field">
	            <%= f.label :year_built, 'Year built:' %>
	            <%= @listing.year_built %>
	          </div>
	          <div class="hidden-md hidden-sm hidden-xs">
	            <br/><br/>
	          </div>
	          <div class="field">
	            <%= f.label :baths, 'Baths:' %>
	            <%= @listing.baths %>
	          </div>
	        </div>
	        <div class="col-lg-2">
	          <div class="field">
	            <%= f.label :price_per_sqft, 'Price per sqft:' %>
	            <%= @listing.price_per_sqft %>
	          </div>
	          <div class="hidden-md hidden-sm hidden-xs">
	            <br/><br/>
	          </div>
	          <div class="field">
	            <%= f.label :lot_size, 'Lot size:' %>
	            <%= @listing.lot_size %>
	          </div>
	        </div>
	        <div class="col-lg-2">
	          <div class="field">
	            <%= f.label :mls_id, 'MLS ID:' %>
	            M<%= @listing.mls_id %>
	          </div>
	        </div>
      	</div>
        <div class="col-lg-1 text-center">
        	<%= link_to 'Edit', listing_path(@listing), :class=>'btn btn-sm btn-primary' %>
          <p></p>
          <%= link_to activate_listing_listings_path(@listing), :class=>'btn btn-sm btn-danger', method: :post do %>
          	<%= @listing.status == 'Active' ? 'Deactivate' : 'Activate' %>
          <% end %>
          <p></p>
          <%= link_to 'Update', listing_path(@listing), :class=>'btn btn-sm btn-success' %>
        </div>
      </div>
      <div class="div-showing">
      	<div class="col-lg-4 col-offset-lg-8">
	      	<%= f.label :agent_id, 'Agent:' %>
	      	<%= f.select :agent_id, @agents, {}, :class => 'js-select' %>
	      </div>
      </div>
      <div class="div-showing">
      	<div class="col-lg-12">
	      	<div class="field">
	      		<%= f.label :description, 'Description:', :style=>'vertical-align:top;' %>
	      		<%= f.text_area :description, :rows=>'6', :class=>'form-control' %>
	      	</div>
	      </div>
      	<div class="field">
      		<div class="col-lg-12">
	      		<%= f.label :agent_id, 'Pictures:', :style=>'vertical-align:top' %>
	      		<%= image_tag @pics.first.avatar.url(:large), height: '135' %>
	        </div>
      	</div>
      </div>
    </div>
  </div>
<% end %>