config/routes.rb
Rails.application.routes.draw do

  root :to => 'dashboards#index'
  devise_for :agents

  resources :agents do
    collection do
      post :index 
      post :cnew
      post :search
      post :activate_agent
    end
  end    

  resources :listings do
    collection do
      post :search
      post :activate_listing
    end
  end

  resources :users do
    collection do
      post :index
      post :activate_user
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	def activate?
    value = self.status == 'Active' ? 'Inactive' : 'Active'
    self.status = value
    self.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_agent!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    if !params[:status].blank?
      @users = @users.where( :status=>params[:status] )
      @status = params[:status]
    end

    if !params[:state].blank?
      @users = @users.where( :state=>params[:state] )
      @state = params[:state]
    end

    if !params[:search].blank?
      @search = params[:search]
      @users = @users.where("first_name LIKE ? OR last_name LIKE ? OR email LIKE ? OR fb_id LIKE ?", "%#{@search}%", "%#{@search}%", "%#{@search}%", "%#{@search}%")
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def activate_user
    @user = User.find(params[:format])
    @user.activate?
    redirect_to user_path(@user)
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :fb_id, :username, :email, :country, :status, :state)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :fb_id %><br>
    <%= f.text_field :fb_id %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_users.html.erb
<div class="table-responsive">
  <table id="table_users">
    <thead>
      <tr>
        <th>ID</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Facebook ID</th>
        <th>State</th>
        <th>Status</th>
        <th colspan="2" class="text-center">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr data-link="<%= user_path(user)%>">
          <td>U<%= user.id %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.email %></td>
          <td><%= user.fb_id %></td>
          <td><%= user.state %></td>
          <td><span class="<%= user.status == 'Active' ? 'active' : 'inactive' %>"><%= user.status %></span></td>
          <td>
            <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-sm btn-danger btn-action' do %>
              <i class="fa fa-trash"></i>
            <% end %>
          </td>
          <td><%= link_to 'view/edit', user_path(user), :class=>'btn btn-sm btn-primary btn-action' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% content_for(:side_bar) do %>
  <%= render 'dashboards/leftsidebar' %>
<% end %>

<div class="div-users">
  <div class="col-lg-12">
    <div class="div-search">
      <%= simple_form_for(:agents, url: users_path, method: :post) do %>
        <div class="col-lg-6 div-nopadding">
          <div class="col-lg-6 div-margin-bottom">
            <label>Status:</label>
            <%= select_tag "status", options_for_select(["", "Active", "Inactive" ], @status), :class=>'js-select', "data-placeholder" => "Select..." %>
          </div>
          <div class="col-lg-6 div-margin-bottom">
            <label>State:</label>
            <%= select_tag "state", options_for_select(t('state_names'), @state), :class=>'js-select', "data-placeholder" => "Select..."  %>
          </div>
        </div>
        <div class="col-lg-6 div-nopadding">
          <div class="col-lg-9 div-margin-bottom">
            <label>Search:</label>
            <%= text_field_tag "search", nil, :class=>"form-control", :autocomplete=>"off", :value=>@search %>
          </div>
          <div class="col-lg-3">
            <%= button_tag(type: 'submit', :class=>'btn btn-primary') do %>
              Search
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="div-existing" id="div-userstable">
      <%= render 'users' %>
    </div>
  </div>
</div> 

app/views/users/index.js.erb
jQuery('#div-userstable').html("<%= j(render 'users') %>");

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% content_for(:side_bar) do %>
  <%= render 'dashboards/leftsidebar' %>
<% end %>

<%= form_for(@user) do |f| %>
  <div class="div-users">
    <div class="col-lg-12">
      <div class="div-backuser">
        <%= link_to '< Back', users_path, :class=>'btn btn-default' %>
      </div>
      <div class="div-showing">
        <div class="col-lg-3">
          <div class="field">
            <%= f.label :id, 'user ID:' %>
            <%= @user.id %>
          </div>
          <div class="hidden-md hidden-sm hidden-xs">
            <br/><br/>
          </div>
          <div class="field">
            <%= f.label :fb_id, 'Facebook ID:' %>
            <%= @user.fb_id %>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="field">
            <%= f.label :first_name, 'First name:' %>
            <%= @user.first_name %>
          </div>
          <div class="hidden-md hidden-sm hidden-xs">
            <br/><br/>
          </div>
          <div class="field">
            <%= f.label :last_name, 'Last name:' %>
            <%= @user.last_name %>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="field">
            <%= f.label :username, 'Username:' %>
            <%= @user.username %>
          </div>
          <div class="hidden-md hidden-sm hidden-xs">
            <br/><br/>
          </div>
          <div class="field">
            <%= f.label :email, 'Email:' %>
            <%= @user.email %>
          </div>
        </div>
        <div class="col-lg-2">
          <div class="hidden-md hidden-sm hidden-xs">
            <br/><br/><br/>
          </div>
          <div class="field">
            <%= f.label :country, 'Country:' %>
            <%= @user.country %>
          </div>
        </div>
        <div class="col-lg-1 text-center">
          <%= link_to activate_user_users_path(@user), :class=>'btn btn-sm btn-danger', method: :post do %>
            <%= @user.status == 'Active' ? 'Deactivate' : 'Activate' %>
          <% end %>
        </div>
      </div>
      <h4>Favorited properties</h4>
      <div class="div-existing">
        <div class="table-responsive">
          <table>
            <thead>
              <tr>
                <th>Property ID</th>
                <th>Walk score</th>
                <th>Beds</th>
                <th>Baths</th>
                <th>Year Built</th>
                <th>Lot size</th>
                <th>Price per sqft</th>
                <th>Assigned broker</th>
              </tr>
            </thead>

            <tbody>
              <%# @user.each do |user| %>
                <tr>
                  <td><%=  %></td>
                  <td><%=  %></td>
                  <td><%=  %></td>
                  <td><%=  %></td>
                  <td><%=  %></td>
                  <td><%=  %></td>
                  <td><%=  %></td>
                  <td><%=  %></td>
                </tr>
              <%# end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>