config/routes.rb
Rails.application.routes.draw do

  root :to => 'dashboards#index'
  devise_for :agents

  resources :agents do
    collection do
      post :index 
      post :cnew
      post :search
      post :activate_agent
    end
  end    

  resources :listings do
    collection do
      post :search
      post :activate_listing
    end
  end

  resources :users do
    collection do
      post :index
      post :activate_user
    end
  end
end

app/models/agent.rb
class Agent < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, 
    :path => ":rails_root/public/system/:class/:attachement/:id/:basename_:style.:extension",
    :url => "/system/:class/:attachement/:id/:basename_:style.:extension",
    :styles => {
      :thumb    => ['100x100#',  :jpg, :quality => 70],
      :preview  => ['480x480#',  :jpg, :quality => 70],
      :large    => ['600>',      :jpg, :quality => 70],
      :retina   => ['1200>',     :jpg, :quality => 30]
    },
    :convert_options => {
      :thumb    => '-set colorspace sRGB -strip',
      :preview  => '-set colorspace sRGB -strip',
      :large    => '-set colorspace sRGB -strip',
      :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
    }

  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
  # validates_attachment :avatar,
  #   :presence => true,
  #   :size => { :in => 0..10.megabytes },
  #   :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }

  # validates :name,
  #   :presence => true,
  #   :uniqueness => true

  def activate?
    value = self.status == 'Active' ? 'Inactive' : 'Active'
    self.status = value
    self.save
  end

end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :authenticate_agent!
  before_action :set_agent, only: [:show, :edit, :update, :destroy]

  def index
  	if flash[:search].blank?
			@agents = Agent.where('id!=?', 1)
		else
			s_params = flash[:search]
			@agents = Agent.where('id!=?', 1)

			if !s_params["status"].blank?
	      @agents = @agents.where( :status=>s_params["status"] )
	      @status = s_params["status"]
	    end

	    if !s_params["state"].blank?
	      @agents = @agents.where( :state=>s_params["state"] )
	      @state = s_params["state"]
	    end

	    if !s_params["search"].blank?
	      @search = s_params["search"]
	      @agents = @agents.where("first_name LIKE ? OR last_name LIKE ? OR email LIKE ?", "%#{@search}%", "%#{@search}%", "%#{@search}%")
	    end
	  end
  end

  def cnew
		agent = Agent.new(agent_params)
		agent.status = "Active"
		
		begin
		  agent.save!(validate: false)
		rescue => ex
		  logger.error ex.message
		end

		redirect_to agents_path
  end

  def show
  	@agent = Agent.find_by_id(params[:id])
  end

  def activate_agent
  	@agent = Agent.find(params[:format])
  	@agent.activate?
  	redirect_to agent_path(@agent)
  end

  def search
    redirect_to agents_path, flash: { search: search_params }
  end

  def destroy
    @agent.destroy
    respond_to do |format|
      format.html { redirect_to agents_url, notice: 'Agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private 
  	def set_agent
      @agent = Agent.find(params[:id])
    end

	  def agent_params
	  	params.permit(:first_name, :last_name, :password, :password_confirmation, :avatar, :email)
	  end

	  def search_params
      params.permit(:status, :state, :search)
    end
end

app/views/agents/_agents.html.erb
<div class="table-responsive">
  <table>
    <thead>
      <th>Agent ID</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>State</th>
      <th>Status</th>
      <th class="text-center" colspan="2">Action</th>
    </thead>
    <tbody>
      <% @agents.each do |a| %>
        <tr data-link="<%= agent_path(a)%>">
          <td>A<%= a.id %></td>
          <td><%= a.first_name %></td>
          <td><%= a.last_name %></td>
          <td><%= a.email %></td>
          <td><%= a.state %></td>
          <td><span class="<%= a.status == 'Active' ? 'active' : 'inactive' %>"><%= a.status %></span></td>
          <td>
            <%= link_to a, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-sm btn-danger btn-action' do %>
              <i class="fa fa-trash"></i>
            <% end %>
          </td>
          <td><%= link_to 'view/edit', agent_path(a), :class=>'btn btn-sm btn-primary btn-action' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/agents/index.html.erb
<% content_for(:side_bar) do %>
	<%= render 'dashboards/leftsidebar' %>
<% end %>

<div class="div-agents">
	<div class="col-lg-12">
    <div class="div-newagent">
      <button class="btn btn-success" data-toggle="modal" id="btn_newagent">Create new agent</button>
    </div>
		<div class="div-search">
      <%= simple_form_for(:agents, url: search_agents_path, method: :post) do %>
        <div class="col-lg-6 div-nopadding">
          <div class="col-lg-6 div-margin-bottom">
            <label>Status:</label>
            <%= select_tag "status", options_for_select(["", "Active", "Inactive"], @status), :class=>'js-select', "data-placeholder" => "Select..." %>
          </div>
          <div class="col-lg-6 div-margin-bottom">
            <label>State:</label>
            <%= select_tag "state", options_for_select(t("state_names"), @state), :class=>'js-select', "data-placeholder" => "Select..."  %>
          </div>
        </div>
        <div class="col-lg-6 div-nopadding">
          <div class="col-lg-9 div-margin-bottom">
            <label>Search:</label>
            <%= text_field_tag "search", nil, :class=>"form-control", :autocomplete=>:off, :value=>@search %>
          </div>
          <div class="col-lg-3">
            <%= button_tag(type: 'submit', :class=>'btn btn-primary') do %>
              Search
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="div-existing" id="div-agentstable">
      <%= render 'agents' %>
    </div>
	</div>
</div>

<div class="modal fade" id="newAgent" tabindex="-1" role="dialog" aria-labelledby="newAgentLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="newAgentLabel">New Agent Creator</h4>
      </div>
      <%= simple_form_for(:newagent, url: cnew_agents_path, method: :post, :id=>'form_new_agent', html: {multipart: true}) do %>
        <div class="modal-body">
          <div class="field text-center">
            <%#= file_field_tag :avatar %>
            <label for="file-upload" class="custom-file-upload" style="border:1px solid #9A9590;padding:2em;color:#9A9590;width:auto;">
              <i class="fa fa-plus-circle" style="font-size:5em;"></i><br/>UPLOADING<br/>PROFILE PICTURE
            </label>
            <input id="file-upload" type="file" style="display:none" name="avatar" required="required" />
          </div>
          <div class="field">
            <label>First name:</label>
            <%= text_field_tag "first_name", nil, :class=>'form-control', :required=>true, autocomplete: "off" %>
          </div>    
          <div class="field">
            <label>Last name:</label>
            <%= text_field_tag "last_name", nil, :class=>'form-control', :required=>true, autocomplete: "off" %>
          </div>    
          <div class="field">
            <label>Email:</label>
            <%= email_field_tag "email", nil, :class=>'form-control', :required=>true, autocomplete: "off" %>
          </div>    
          <div class="field">
            <label>Password:</label>
            <%= password_field_tag "password", nil, :class=>'form-control', :required=>true %>
          </div>    
          <div class="field">
            <label>Confirm Password:</label>
            <%= password_field_tag "password_confirmation", nil, :class=>'form-control', :required=>true %>
          </div>    
        </div>
        <div class="modal-body text-center">
          <%= button_tag(type: 'submit', :class=>'btn btn-primary', :id=>'btn_createagent') do %>
            Create Agent
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/agents/index.js.erb
jQuery('#div-agentstable').html("<%= j(render 'agents') %>");

app/views/agents/show.html.erb
<% content_for(:side_bar) do %>
	<%= render 'dashboards/leftsidebar' %>
<% end %>

<%= form_for(@agent) do |f| %>
	<div class="div-agents">
		<div class="col-lg-12">
	    <div class="div-backagent">
	      <%= link_to '< Back', agents_path, :class=>'btn btn-default' %>
	    </div>
	    <div class="div-showing">
	    	<div class="col-lg-3">
	    		<div class="field">
		    		<%= f.label :id, 'Agent ID:' %>
						<%= @agent.id %>
					</div>
					<div class="hidden-md hidden-sm hidden-xs">
						<br/><br/>
					</div>
					<div class="field">
						<%= f.label :status, 'Status:' %>
						<span class="<%= @agent.status == 'Active' ? 'active' : 'inactive' %>">
							<%= @agent.status %>
						</span>
					</div>
	    	</div>
	    	<div class="col-lg-3">
	    		<div class="field">
		    		<%= f.label :first_name, 'First name:' %>
						<%= @agent.first_name %>
					</div>
					<div class="hidden-md hidden-sm hidden-xs">
						<br/><br/>
					</div>
					<div class="field">
						<%= f.label :last_name, 'Last name:' %>
						<%= @agent.last_name %>
					</div>
	    	</div>
	    	<div class="col-lg-5">
	    		<div class="field">
		    		<%= f.label :country, 'Country:' %>
						<%= @agent.country %>
					</div>
					<div class="hidden-md hidden-sm hidden-xs">
						<br/><br/>
					</div>
					<div class="field">
						<%= f.label :email, 'Email:' %>
						<%= @agent.email %>
					</div>
	    	</div>
	    	<div class="col-lg-1 text-center">
          <%= link_to 'Edit', agent_path(@agent), :class=>'btn btn-sm btn-primary' %>
          <p></p>
          <%= link_to activate_agent_agents_path(@agent), :class=>'btn btn-sm btn-danger', method: :post do %>
          	<%= @agent.status == 'Active' ? 'Deactivate' : 'Activate' %>
          <% end %>
          <p></p>
          <%= link_to 'Update', agent_path(@agent, todo: 'activate'), :class=>'btn btn-sm btn-success' %>
          <%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
	    	</div>
	    </div>
			<div class="div-showing">
				<div class="col-lg-6">
					<%= f.label :description, 'Description: ', :style=>'vertical-align:top' %>
					<%= f.text_area :description, :class=>'form-control', :placeholder=>'Enter Keyword...', :rows=>'6' %>
				</div>
				<div class="col-lg-4">
					<%= f.label :avatar, 'Profile picture:', :style=>'width:100%' %>
					<%= f.file_field :avatar %>
				</div>
				<div class="col-lg-2 text-right">
					<div class="div-avatar">
						<%= image_tag @agent.avatar.url(:large), height: '135' %>
					</div>
				</div>
			</div>
			<h4>Assigned properties</h4>
			<div class="div-existing">
				<div class="table-responsive">
		      <table>
		        <thead>
		          <tr>
		            <th>Property ID</th>
		            <th>Walk score</th>
		            <th>Beds</th>
		            <th>Baths</th>
		            <th>Year Built</th>
		            <th>Lot size</th>
		            <th>Price per sqft</th>
		            <th>Assigned broker</th>
		          </tr>
		        </thead>

		        <tbody>
		          <%# @agent.each do |user| %>
		            <tr>
		              <td><%=  %></td>
		              <td><%=  %></td>
		              <td><%=  %></td>
		              <td><%=  %></td>
		              <td><%=  %></td>
		              <td><%=  %></td>
		              <td><%=  %></td>
		              <td><%=  %></td>
		            </tr>
		          <%# end %>
		        </tbody>
		      </table>
		    </div>
    	</div>
		</div>
	</div>
<% end %>